### ISSUE TITLE
env_file not working

### ISSUE THREAD

**Issue by mustela** [dduportal-dockerfiles/docker-compose#8]
I have the following docker-compose file and I'm using the alias ("Convenience mode")  to run docker-compose, but it seems that it can't read the env file (it exists)

```
portal:
  image: portal:testing
  env_file:
    - /home/lab/portal-env.txt

```

```
docker-compose  -f docker-compose-portal.yml up
```

Result: 

```
Couldn't find env file: /home/lab/portal-env.txt
```

I've tried mounting the path, but didn't work. 

Any clue ?
